name: Daily Weather Update

on:
  schedule:
    # Run daily at 12:00 PM UTC (adjust timezone as needed)
    # This is 8:00 AM EST / 7:00 AM EDT
    - cron: "0 12 * * *"

  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  send-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Send weather update
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: npm start
