name: Daily Weather Update

on:
  schedule:
    # Run daily at 12:00 AM New York time (Eastern Time)
    # This is 5:00 AM UTC during EST, 4:00 AM UTC during EDT
    - cron: "0 5 * * *"

  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  send-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Send weather update
        env:
          # Regional configuration (JSON string containing all regions with webhook URLs)
          REGIONS_CONFIG: ${{ secrets.REGIONS_CONFIG }}

          # Weekly forecast webhook URL (for consolidated weekly forecasts)
          WEEKLY_FORECAST_WEBHOOK_URL: ${{ secrets.WEEKLY_FORECAST_WEBHOOK_URL }}
        run: npm start
